POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
    "username": "priyanshuchaurasia",
    "password": "Priya@123456",
    "email": "priyanshuchaurasia@gmail.com",
    "name": "Priyanshu Chaurasia"
}
###

POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
  "email": "priyanshu@gmail.com",
  "password": "Priya@1234"
  
}

 ###

GET http://localhost:9090/get_user_and_profile 
Content-Type: application/json

{
    "token":"713cd5210e452cddd42ceb361af2fa57c8d032bb2c2d3a98e2226d610f25f315"
}

###

POST http://localhost:9090/update_profile_data
Content-Type: application/json

{
  "token": "713cd5210e452cddd42ceb361af2fa57c8d032bb2c2d3a98e2226d610f25f315",
   "bio": "",
  "currentPost": "CEO",
  "pastWork": [
    {
        "company": "Microsoft",
        "position": "Software Engineer",
        "years": "5+ years"
    }
  ],
  "education": [
    {
        "school": "NIIT",
        "degree": "B.Tech in Computer Science",
        "years": "2020-2024"
    }
  ]
}

###

GET http://localhost:9090/user/get_all_users




# http://localhost:9090/user/download_resume?id=688cbcc1c43e315e0bcc9e25 
{
  "Name": "Priyanshu Chaurasia",
  "Email": "PriyanshuChaurasia395@gmail.com"
}


# Post http://localhost:9090/post in form data upload token body and media details




