POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
    "username": "priyanshu",
    "password": "Priya@1234",
    "email": "priyanshu@gmail.com",
    "name": "Priyanshu Chaurasia"
}

POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
     "email": "priyanshu@gmail.com",
    "password": "Priya@1234"
}

GET http://localhost:9090/get_user_and_profile 
Content-Type: application/json

{
    "token":"your_jwt_token_here"
}



